version: "3.8"

services:
  api1:
    container_name: api1
    image: "${IMAGE_REPO}:${BUILD_TAG}"
    env_file: .env
    ports:
      - "4000:4000"
    restart: always

  api2:
    container_name: api2
    image: "${IMAGE_REPO}:${BUILD_TAG}"
    env_file: .env
    ports:
      - "4001:4000"
    restart: always

  api3:
    container_name: api3
    image: "${IMAGE_REPO}:${BUILD_TAG}"
    env_file: .env
    ports:
      - "4002:4000"
    restart: always
