version: "3.8"
services:
  api1:
    image: ${IMAGE_REPO}:${BUILD_TAG}
    container_name: api1
    restart: always
    env_file: [.env.api1]
    ports: ["4000:4000"]
    working_dir: /app
    command: node dist/main.js

  api2:
    image: ${IMAGE_REPO}:${BUILD_TAG}
    container_name: api2
    restart: always
    env_file: [.env.api2]
    ports: ["4001:4001"]
    working_dir: /app
    command: node dist/main.js

  api3:
    image: ${IMAGE_REPO}:${BUILD_TAG}
    container_name: api3
    restart: always
    env_file: [.env.api3]
    ports: ["4002:4002"]
    working_dir: /app
    command: node dist/main.js
