name: Deploy Multi License API (reuse platform-main)
on:
  workflow_dispatch:
    inputs:
      ENV:
        description: "Environment to deploy (dev/stage/prod)"
        required: true
        default: "stage"
      ROLLBACK_TAG:
        description: "If set, deploy that tag"
        required: false
      GIT_REF:
        description: "Git ref/branch to use"
        required: false
        default: "main"
# (rest of the file unchanged)
