name: Destroy Multi License API Infrastructure

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: "Environment to destroy (dev/stage/prod)"
        required: true
        default: "stage"

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'ap-south-1' }}
  TF_REGION:  ${{ vars.AWS_REGION || 'ap-south-1' }}
  # Optional overrides via repo variables
  ECR_REPO_NAME: ${{ vars.ECR_REPO_NAME }}
  EC2_INSTANCE_NAME_PATTERN: ${{ vars.EC2_INSTANCE_NAME_PATTERN || format('{0}-idlms-app', github.event.inputs.ENV) }}

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENV }}
    permissions:
      contents: read

    steps:
      - name: Checkout (feature/btl-77)
        uses: actions/checkout@v4
        with:
          ref: feature/btl-77

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Get AWS Account ID
        id: aws-account
        run: |
          echo "account_id=$(aws sts get-caller-identity --query Account --output text)" >> "$GITHUB_OUTPUT"

      - name: Set TF bucket and artifact bucket
        run: |
          echo "TF_BUCKET=${{ github.event.inputs.ENV }}-btl-idlms-backend-api-tfstate-${{ steps.aws-account.outputs.account_id }}" >> $GITHUB_ENV
          echo "BACKUP_BUCKET=idlms-${{ github.event.inputs.ENV }}-website-built-artifact-${{ steps.aws-account.outputs.account_id }}" >> $GITHUB_ENV
          echo "Using TF_BUCKET=$TF_BUCKET"
          echo "Using BACKUP_BUCKET=$BACKUP_BUCKET"

      # ────────────────────── STOP APP FIRST (EC2 via SSM) ──────────────────────
      - name: Resolve EC2 instance by Name tag (best effort)
        id: resolve-iid
        continue-on-error: true
        run: |
          set -euo pipefail
          NAME="${EC2_INSTANCE_NAME_PATTERN}"
          IID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=${NAME}" "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text \
            --region "${AWS_REGION}" | awk '{print $1}')
          if [ -n "$IID" ] && [ "$IID" != "None" ]; then
            echo "INSTANCE_ID=$IID" >> $GITHUB_ENV
            echo "Resolved INSTANCE_ID=$IID"
          else
            echo "No running instance found for Name='${NAME}'. Continuing."
          fi

      - name: Stop containers on instance (best effort)
        if: env.INSTANCE_ID != ''
        continue-on-error: true
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids "${{ env.INSTANCE_ID }}" \
            --comment "Stop IDLMS containers & cleanup" \
            --parameters 'commands=[
              "set -e",
              "cd /home/ubuntu || exit 0",
              "echo \"Stopping containers if present...\"",
              "if command -v docker-compose >/dev/null 2>&1; then docker-compose down || true; fi",
              "if command -v docker >/dev/null 2>&1; then docker ps -q | xargs -r docker stop; fi",
              "if command -v docker >/dev/null 2>&1; then docker ps -aq | xargs -r docker rm -f; fi",
              "echo \"Done.\""
            ]' \
            --timeout-seconds 300 \
            --region "${{ env.AWS_REGION }}"

      # ─────────────────── CLEAN ARTIFACTS (S3 + ECR) ───────────────────
      - name: Empty artifact S3 prefix for this env (best effort)
        continue-on-error: true
        run: |
          set -euo pipefail
          echo "Emptying s3://${BACKUP_BUCKET}/${{ github.event.inputs.ENV }}/ ..."
          aws s3 rm "s3://${BACKUP_BUCKET}/${{ github.event.inputs.ENV }}/" --recursive --region "${AWS_REGION}" || true

      - name: Derive ECR repo URL / region
        id: ecr-derive
        continue-on-error: true
        run: |
          set -euo pipefail
          ACCOUNT_ID="${{ steps.aws-account.outputs.account_id }}"
          # default repo name is "<env>-idlms-api" unless ECR_REPO_NAME override provided
          REPO_NAME="${ECR_REPO_NAME:-${{ github.event.inputs.ENV }}-idlms-api}"
          # prefer configured region
          ECR_REGION="${AWS_REGION}"
          # if repo not in this region, try a couple common fallbacks
          if ! aws ecr describe-repositories --repository-names "$REPO_NAME" --region "$ECR_REGION" >/dev/null 2>&1; then
            for R in ap-south-1 ap-southeast-1; do
              if [ "$R" != "$ECR_REGION" ] && aws ecr describe-repositories --repository-names "$REPO_NAME" --region "$R" >/dev/null 2>&1; then
                ECR_REGION="$R"; break
              fi
            done
          fi
          if aws ecr describe-repositories --repository-names "$REPO_NAME" --region "$ECR_REGION" >/dev/null 2>&1; then
            echo "ECR_REPO_URL=${ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${REPO_NAME}" >> $GITHUB_ENV
            echo "ECR_REGION=${ECR_REGION}" >> $GITHUB_ENV
            echo "Resolved ECR_REPO_URL=${ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${REPO_NAME}"
          else
            echo "No ECR repository found for $REPO_NAME — skipping ECR purge."
          fi

      - name: Purge all images in ECR repo (best effort)
        if: env.ECR_REPO_URL != ''
        continue-on-error: true
        run: |
          set -euo pipefail
          REPO_NAME="$(echo "${ECR_REPO_URL}" | cut -d/ -f2)"
          echo "Purging ALL images in $REPO_NAME (${ECR_REGION}) ..."
          # delete tagged + untagged images in batches
          while : ; do
            IDS=$(aws ecr list-images --repository-name "$REPO_NAME" --region "${ECR_REGION}" --query 'imageIds' --output json)
            COUNT=$(echo "$IDS" | jq 'length')
            [ "$COUNT" -eq 0 ] && { echo "No more images."; break; }
            echo "$IDS" | jq -c '.[:100]' > batch.json
            aws ecr batch-delete-image --repository-name "$REPO_NAME" --image-ids file://batch.json --region "${ECR_REGION}" || true
          done
          echo "ECR purge complete."

      # ───────────────────── TF DESTROY (safe order) ─────────────────────
      - name: Destroy CloudWatch (skip if missing)
        run: |
          if [ ! -d infra/cloudwatch ]; then echo "infra/cloudwatch not found; skipping"; exit 0; fi
          cd infra/cloudwatch
          terraform init \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=${{ github.event.inputs.ENV }}/cloudwatch/terraform.tfstate" \
            -backend-config="region=${TF_REGION}"
          terraform destroy -auto-approve -var-file="${{ github.event.inputs.ENV }}.tfvars"

      - name: Destroy API Gateway (skip if missing)
        run: |
          if [ ! -d infra/rest-api ]; then echo "infra/rest-api not found; skipping"; exit 0; fi
          cd infra/rest-api
          terraform init \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=${{ github.event.inputs.ENV }}/rest-api/terraform.tfstate" \
            -backend-config="region=${TF_REGION}"
          terraform destroy -auto-approve -var-file="${{ github.event.inputs.ENV }}.tfvars"

      - name: Destroy NLB (skip if missing)
        run: |
          if [ ! -d infra/nlb ]; then echo "infra/nlb not found; skipping"; exit 0; fi
          cd infra/nlb
          terraform init \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=${{ github.event.inputs.ENV }}/nlb/terraform.tfstate" \
            -backend-config="region=${TF_REGION}"
          terraform destroy -auto-approve -var-file="${{ github.event.inputs.ENV }}.tfvars"

      - name: Destroy ECR (skip if missing)
        run: |
          if [ ! -d infra/ecr ]; then echo "infra/ecr not found; skipping"; exit 0; fi
          cd infra/ecr
          terraform init \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=${{ github.event.inputs.ENV }}/ecr/terraform.tfstate" \
            -backend-config="region=${TF_REGION}"
          terraform destroy -auto-approve -var-file="${{ github.event.inputs.ENV }}.tfvars"

      - name: Destroy SSM (skip if missing)
        run: |
          if [ ! -d infra/ssm ]; then echo "infra/ssm not found; skipping"; exit 0; fi
          cd infra/ssm
          terraform init \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=${{ github.event.inputs.ENV }}/ssm/terraform.tfstate" \
            -backend-config="region=${TF_REGION}"
          terraform destroy -auto-approve -var-file="${{ github.event.inputs.ENV }}.tfvars"

      - name: Empty S3 bucket prefix again (best effort)
        continue-on-error: true
        run: |
          aws s3 rm "s3://${BACKUP_BUCKET}/${{ github.event.inputs.ENV }}/" --recursive --region "${AWS_REGION}" || true

      - name: Destroy S3 (skip if missing)
        run: |
          if [ ! -d infra/s3 ]; then echo "infra/s3 not found; skipping"; exit 0; fi
          cd infra/s3
          terraform init \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=${{ github.event.inputs.ENV }}/s3/terraform.tfstate" \
            -backend-config="region=${TF_REGION}"
          terraform destroy -auto-approve -var-file="${{ github.event.inputs.ENV }}.tfvars"

      - name: Destroy VPC (skip if missing)
        run: |
          if [ ! -d infra/vpc ]; then echo "infra/vpc not found; skipping"; exit 0; fi
          cd infra/vpc
          terraform init \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=${{ github.event.inputs.ENV }}/vpc/terraform.tfstate" \
            -backend-config="region=${TF_REGION}"
          terraform destroy -auto-approve -var-file="${{ github.event.inputs.ENV }}.tfvars"
