name: DEPRECATED - Use 'Deploy Multi License API (reuse platform-main - single)'
on: { workflow_dispatch: {} }
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::error::Deprecated. Use '.github/workflows/deploy-multi-license-single.yml'."
          exit 1
